@Suppress("ObjectPropertyName")
object Versions {
    const val kotlin = "1.7.10"
    const val `kotlinx-coroutines` = "1.6.4"
    const val scalaBinary = "2.13"
    const val akkaStreamKafka = "2.0.5"
    const val lagom = "1.6.4"
    const val lagomPac4j = "2.1.0"
    const val play = "2.8.2"
    const val ktlint = "0.43.2"
    const val `ktlint-plugin` = "11.0.0"
    const val jacoco = "0.8.7"
    const val junit5 = "5.3.2"
    const val assertj = "3.11.1"
    const val `kafka-junit5` = "3.1.0"
    const val kafka = "2.4.1"
    const val `publish-plugin` = "1.1.0"
    const val dokka = "1.7.10"
    const val `scalafmt-plugin` = "1.16.2"
    const val scalatest = "3.1.1"
    const val jgitver = "0.9.1"
    const val `play-redis-cache` = "2.7.0"
}
