configured-ahc-ws-client {
  logging {
    # Enables or completely disables logging.
    enabled = false
    # List of regexp patterns of URLs to be excluded from logging.
    skip-urls = []
    # Logging presets. Available elements:
    #   curl - log as curl request (for request only)
    #   body - log body
    #   headers - log headers
    #   cookies - log cookies
    default-preset {
      request-elements = ["curl"]
      response-elements = ["body", "headers", "cookies"]
    }
    # Each preset contains request-elements + response-elements like default-preset, urls (list of regexp patterns of URLs)
    # and http-codes (list of http response codes for which this preset is applicable, or empty list for no restrictions):
    # {
    #   request-elements = ["curl"]
    #   response-elements = ["headers", "cookies"]
    #   urls = ["/foo/([^/][0-9]+)/bar"]
    #   http-codes = [200]
    # }
    # {
    #   request-elements = ["curl"]
    #   response-elements = ["body", "headers", "cookies"]
    #   urls = ["/foo/([^/][0-9]+)/bar"]
    # }
    presets = []
  }
}
