configured-ahc-ws-client {
  logging {
    # Enables or completely disables logging.
    enabled = false
    # List of regexp patterns of URLs to be excluded from logging.
    skip-urls = []
    # Logging presets. Available elements:
    #   curl - log as curl request (for request only)
    #   body - log body
    #   headers - log headers
    #   cookies - log cookies
    default-preset {
      request-elements = ["curl"]
      response-elements = ["body", "headers", "cookies"]
    }
    # Each preset contains request-elements + response-elements like default-preset, and urls (list of regexp patterns of URLs):
    # {
    #   request-elements = ["curl"]
    #   response-elements = ["body", "headers", "cookies"]
    #   urls = ["/foo/([^/][0-9]+)/bar"]
    # }
    presets = []
  }
}
